# More info on config here: https://golangci-lint.run/usage/configuration/#config-file
run:
  timeout: 5m
  tests: false
linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - tagliatelle
    - wrapcheck
  fast: false
linters-settings:
  gocritic:
    enabled-tags:
      - style
      - experimental
      - performance
      - diagnostic
      - opinionated

  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

  gci:
    local-prefixes: github.com/loghole/collector

  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - .Wrapf(
      - .Wrap(
      - .WithCode(
      - .ValidateStruct(
